# Victorious MARKET -- Status & Metrics Generator (PowerShell)
# Part of Victorious MARKET Multi-AI Engineering Control System Specification v3 (Sections 22.4, 30.4)

$ErrorActionPreference = "Stop"

Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host " Victorious MARKET -- Status & Metrics Generator           " -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan

$TicketsRoot = ".ai\tickets"
$StateCounts = [ordered]@{
    "BACKLOG"             = 0
    "READY"               = 0
    "ASSIGNED"            = 0
    "IN_PROGRESS"         = 0
    "IMPLEMENTED"         = 0
    "SELF_CHECKED"        = 0
    "UNDER_REVIEW"        = 0
    "CHANGES_REQUIRED"    = 0
    "REVIEW_APPROVED"     = 0
    "INTEGRATION_TESTING" = 0
    "RELEASE_CANDIDATE"   = 0
    "RELEASED"            = 0
    "CANCELLED"           = 0
}

$BlockedTickets = @()
$EscalatedTickets = @()

$TicketFiles = Get-ChildItem -Path $TicketsRoot -Recurse -Filter "*.md" | Where-Object { $_.Name -ne "README.md" }

foreach ($f in $TicketFiles) {
    $content = Get-Content -Path $f.FullName -Raw
    $status = "UNKNOWN"
    if ($content -match "Status:\s*([A-Za-z_]+)") {
        $status = $Matches[1].Trim()
        if ($StateCounts.Contains($status)) {
            $StateCounts[$status]++
        }
    }

    if ($content -match "Blocked:\s*yes\s*\(ESCALATED\)") {
        $EscalatedTickets += @{ Name = $f.Name; Path = $f.FullName; Reason = "Exceeded cycle/time limit" }
    } elseif ($content -match "Blocked:\s*yes\s*(.*)") {
        $reason = $Matches[1].Trim()
        $BlockedTickets += @{ Name = $f.Name; Path = $f.FullName; Reason = $reason }
    }
}

$Now = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss UTC")

# 1. Generate .ai/status/STATUS.md
$StatusMd = @"
# Victorious MARKET -- System Pipeline Status

> **SCRIPT-GENERATED FILE -- DO NOT EDIT BY HAND**  
> Generated by: `scripts/release/generate-status.ps1`  
> Timestamp: $Now

---

## 1. Ticket Counts by Lifecycle State

| State | Count |
|-------|-------|
| BACKLOG | $($StateCounts["BACKLOG"]) |
| READY | $($StateCounts["READY"]) |
| ASSIGNED | $($StateCounts["ASSIGNED"]) |
| IN_PROGRESS | $($StateCounts["IN_PROGRESS"]) |
| IMPLEMENTED | $($StateCounts["IMPLEMENTED"]) |
| SELF_CHECKED | $($StateCounts["SELF_CHECKED"]) |
| UNDER_REVIEW | $($StateCounts["UNDER_REVIEW"]) |
| CHANGES_REQUIRED | $($StateCounts["CHANGES_REQUIRED"]) |
| REVIEW_APPROVED | $($StateCounts["REVIEW_APPROVED"]) |
| INTEGRATION_TESTING | $($StateCounts["INTEGRATION_TESTING"]) |
| RELEASE_CANDIDATE | $($StateCounts["RELEASE_CANDIDATE"]) |
| RELEASED | $($StateCounts["RELEASED"]) |
| CANCELLED | $($StateCounts["CANCELLED"]) |

---

## 2. Blocked & Escalated Tickets

### Escalated Tickets (Immediate Human Intervention Required)
$($EscalatedTickets.Count) tickets escalated.
"@

if ($EscalatedTickets.Count -gt 0) {
    foreach ($et in $EscalatedTickets) {
        $StatusMd += "`n- **$($et.Name)**: $($et.Reason)"
    }
} else {
    $StatusMd += "`n*(None - pipeline flowing cleanly)*"
}

$StatusMd += @"

### Blocked Tickets
$($BlockedTickets.Count) tickets blocked.
"@

if ($BlockedTickets.Count -gt 0) {
    foreach ($bt in $BlockedTickets) {
        $StatusMd += "`n- **$($bt.Name)**: $($bt.Reason)"
    }
} else {
    $StatusMd += "`n*(None)*"
}

Set-Content -Path ".ai\status\STATUS.md" -Value $StatusMd -Encoding UTF8
Write-Host "[OK] Updated .ai/status/STATUS.md" -ForegroundColor Green

# 2. Generate .ai/status/METRICS.md
$MetricsMd = @"
# Victorious MARKET -- Operational Pipeline Metrics

> **SCRIPT-GENERATED FILE -- DO NOT EDIT BY HAND**  
> Generated by: `scripts/release/generate-status.ps1`  
> Timestamp: $Now

---

## Summary Metrics
- **Total Registered Tickets**: $($TicketFiles.Count)
- **Active Work in Progress (WIP)**: $($StateCounts["ASSIGNED"] + $StateCounts["IN_PROGRESS"] + $StateCounts["UNDER_REVIEW"] + $StateCounts["CHANGES_REQUIRED"])
- **Ready for Release**: $($StateCounts["RELEASE_CANDIDATE"])
- **Successfully Released**: $($StateCounts["RELEASED"])
- **Escalation Rate**: $(if ($TicketFiles.Count -gt 0) { [math]::Round(($EscalatedTickets.Count / $TicketFiles.Count) * 100, 2) } else { 0 })%
"@

Set-Content -Path ".ai\status\METRICS.md" -Value $MetricsMd -Encoding UTF8
Write-Host "[OK] Updated .ai/status/METRICS.md" -ForegroundColor Green
exit 0
